<a href="https://colab.research.google.com/github/manoj-raghav/python/blob/main/20/12/2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [16]:
a=np.random.randint(100,size=(3,3))
a

array([[97, 13, 65],
       [72, 78, 22],
       [98,  0, 37]])

In [23]:
a=np.random.randint(10,size=(10))
a

array([0, 4, 5, 7, 1, 2, 0, 1, 7, 2])

In [24]:
A=np.array([
            [100,30,30]
,
[1,2,3],
[7,8,9]])
B=np.array([
            [90,93,49],
            [1,4,7],
            [5,57,73]
])
A.dot(B)

array([[ 9180, 11130,  7300],
       [  107,   272,   282],
       [  683,  1196,  1056]])

In [31]:
a=np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
])
b=np.array([
            [0,0,0],
            [0,0,0],
            [0,0,0]
])
a.dot(b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
A.T

array([[100,   1,   7],
       [ 30,   2,   8],
       [ 30,   3,   9]])

In [33]:
A.T.dot(B)

array([[9036, 9703, 5418],
       [2742, 3254, 2068],
       [2748, 3315, 2148]])

In [35]:
a@b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])