<a href="https://colab.research.google.com/github/manoj-raghav/python/blob/main/14/12/2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
a=([[10,203,30],[40,50,60]])
c=np.array(a)
np.logical_and(c>20,c<50)

array([[False, False,  True],
       [ True, False, False]])

In [4]:
c.ravel()

array([ 10, 203,  30,  40,  50,  60])

In [10]:
c.reshape(3,2)

array([[ 10, 203],
       [ 30,  40],
       [ 50,  60]])

In [14]:
np.hsplit(c,3)

[array([[10],
        [40]]), array([[203],
        [ 50]]), array([[30],
        [60]])]