<a href="https://colab.research.google.com/github/manoj-raghav/python/blob/main/19/12/2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sys
import numpy as np


In [4]:
a=np.array([1,2,3,4,5])
b=np.array([0,9,8,7,6])


In [5]:
a[0],a[1]

(1, 2)

In [22]:
a[0::4]

array([1, 5])

In [26]:
b[0],b[3]


(0, 7)

In [29]:
b[[0,2,-1]]

array([0, 8, 6])

In [37]:
c=np.array(['a','b','c'])
c.dtype
d=np.array([{'a':1},sys])
d.dtype

dtype('O')

In [42]:
A=np.array([[1,2,3],
           [1,2,3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [43]:
A.shape

(2, 3)

In [45]:
A.ndim

2

In [48]:
c=np.array([
            [
            [1,2,3],
            [4,5,6]
            ],
            [
             [1,2,3],
             [4,5,6]
            ],
            [[1,2,3],
             [4,5,6]
              
            ]
])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [49]:
c.shape

(3, 2, 3)

In [50]:
c.ndim

3

In [65]:
d=np.array([
            [
             [1,2,3],
             [4,5,6]
            ],
            [
             [1,2,3]
             #[1,2,3]
             ]
])

d.shape



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


(2,)

In [66]:
d.size

2