<a href="https://colab.research.google.com/github/manoj-raghav/python/blob/main/19/12/2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A=np.array([
            [1,2,3],
            [4,5,6],
            [7,8,9]
            ])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
A[1]

array([4, 5, 6])

In [4]:
A[1,0]

4

In [6]:
A[1][0]

4

In [7]:
A[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
A[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [11]:
A[1]=[12,23,34]
A

array([[ 1,  2,  3],
       [12, 23, 34],
       [ 7,  8,  9]])

In [13]:
A[2]=0
A

array([[ 1,  2,  3],
       [12, 23, 34],
       [ 0,  0,  0]])

In [14]:
A.sum()

75

In [25]:
A.sum(axis=1)

array([ 6, 69,  0])

In [26]:
A.sum(axis=0)

array([13, 25, 37])